matrix:
    include:
        - language: csharp
          mono: none
          dotnet: 2.1.502
          script:
            - dotnet restore

        - language: node_js
          node_js:
            - node
          cache: npm