matrix:
    include:
        - language: csharp
          mono: none
          dotnet: 2.1.502
          script:
            - dotnet restore

        - language: node_js
          node_js:
              - "stable"
          cache:
              directories:
                  - node_modules
          script:
              - npm test
              - npm run build